[Do not merge yet] Rename `rustc-guide` to `rustc-dev-guide`
rust-lang-nursery/rust-lang-nursery.github.io pull request #4
Opened 2020-03-06 21:36 UTC by LeSeulArtichaut

See rust-lang/rustc-guide#602.

2020-03-07 10:49 UTC, pietroalbini commented
Ping me again when you need this to be merged.

2020-03-09 22:02 UTC, chrissimpkins requested changes
We just need the URL updated here when you have a chance @LeSeulArtichaut.  Thanks!

2020-03-09 22:02 UTC, chrissimpkins commented on rustc-dev-guide/index.html
> +<meta http-equiv="refresh" content="0; URL=https://rust-lang.github.io/rustc-dev-guide/">
Link updated to use https://rustc-dev-guide.rust-lang.org/ instead

```suggestion
<meta http-equiv="refresh" content="0; URL=https://rustc-dev-guide.rust-lang.org/">
```

2020-03-09 22:02 UTC, chrissimpkins commented on rustc-dev-guide/index.html
> +<title>Redirecting to https://rust-lang.github.io/rustc-dev-guide/</title>
```suggestion
<title>Redirecting to https://rustc-dev-guide.rust-lang.org/</title>
```

2020-03-09 22:02 UTC, chrissimpkins commented on rustc-dev-guide/index.html
> +<title>Redirecting to https://rust-lang.github.io/rustc-dev-guide/</title>
Use URL https://rustc-dev-guide.rust-lang.org/ instead

2020-03-09 22:06 UTC, mark-i-m approved these changes

2020-03-09 22:07 UTC, mark-i-m requested changes
Hmm... actually, I think we want the old file name with the redirect URL updated.

2020-03-09 22:08 UTC, LeSeulArtichaut commented
Err... you're right 😅

2020-03-09 22:12 UTC, LeSeulArtichaut commented
Should be good to go now...

2020-03-09 22:13 UTC, mark-i-m approved these changes
Thanks! LGTM

Ping @pietroalbini

2020-03-09 23:12 UTC, chrissimpkins commented
apologies!

2020-03-10 08:56 UTC, merged